export const urls = {
  CHATBOT_URL: 'http://localhost:5002/webhooks/rest/webhook',
  //SERVER_URL: 'http://localhost:8083/magicmonitor/api/v1',
  SERVER_URL: 'http://localhost:8098/api/v1',
  ProjectsList: '/getAllProjectsList',
  BamFilter: '/filteredBamLog',
  LoadProjectMetadata:'/loadProjectMetadata',
  Messages: '/allMessage/',
  Flows: '/flow/',
  TriggersByFlow: '/triggersByFlow/',
  Triggers: '/triggers/',
  TriggersByProject: '/triggersByProject/',
  Locking: '/locking/',
  Subscription: '/PSSData/',
  Scheduler: '/scheduler/',
  InvokeScheduler:'/invokeFlowByScheduler/',
  Summary: '/summary/',
  StartProject: '/startProject',
  StopProject: '/stopRequest/',
  RestartProject: '/restartRequest/',
  Servers: '/serversByProject/',
  ServerWorkersByServerID: '/workerByServerId/',
  ServerWorkersByProject: '/workerByServer/',
  NewServerInstance:'/newServerInstance/',
  StopServer:'/stopServer/',
  StartServer:'/startServer/',
  ClearEntry:'/deleteServer/',
  AllWorkers: '/worker/',
  ActivityLog: '/activityLog',
  ActivityLogMsgFilters: '/getActivityLogMsgFilters',
  ActivityLogWriteMsgFilters: '/writeActivityLogMsgFilters',
  DeleteActivityLog: '/deleteActivityLog',
  ActivityLogCount: '/activityLogCount',
  ODS: '/odsDataByProjectkey/',
  ODSChild: '/odsDataByName?odsname=',
  SpaceInstances: '/getSpaceInstances',
  HostAndEnginesDetails: '/getHostAndEnginesDetails',
  PEAKLICENCE: '/getLicenseProjectDetails/',
  DEFAULTPEAKLICENCE: '/getLicenseDefaultGraph/',
  LICENSECOUNTBYPROJECTANDPEAK: '/getLicenseListProjectDetails/',
  LICENSECOUNTBYPROJECTANDDATE: '/getLicenseProjectDetailsByDate',
  triggerActivity: '/triggersActivityStatistics/',
  alertsByProject: '/alertsByProject/',
  projectLoad: '/flowReqHistory/',
  licenseDetails: '/licenseDetails/',
  updateFlowStatus: '/updateFlowStatus/',
  canWorkEnable: '/canWorkEnable/',
  blob: '/displayblob',
  odsblob: '/displayOdsBlob'
};